"""getexp_core — shared building blocks for every GetExp Python app."""

from getexp_core.config import ConfigError, load_config
from getexp_core.errors import (
    AppError,
    ConflictError,
    ForbiddenError,
    InternalError,
    NotFoundError,
    ProblemDetails,
    RateLimitedError,
    ServiceUnavailableError,
    UnauthorizedError,
    ValidationError,
    to_app_error,
)
from getexp_core.http import (
    CircuitOpenError,
    HttpClient,
    HttpClientOptions,
    RetryOptions,
)
from getexp_core.idempotency import (
    IdempotencyStore,
    InMemoryIdempotencyStore,
    StoredResponse,
    with_idempotency,
)
from getexp_core.logger import configure_logging, get_logger, with_request_id
from getexp_core.result import (
    Err,
    Ok,
    Result,
    err,
    from_awaitable,
    from_callable,
    is_err,
    is_ok,
    map_ok,
    ok,
    unwrap,
    unwrap_or,
)
from getexp_core.storage import (
    BlobStore,
    HealthCheck,
    HealthReport,
    InMemoryBlobStore,
    InMemoryRepository,
    PresignOptions,
    PutOptions,
    Repository,
    check_health,
)

__all__ = [
    "AppError",
    "BlobStore",
    "CircuitOpenError",
    "ConfigError",
    "ConflictError",
    "Err",
    "ForbiddenError",
    "HealthCheck",
    "HealthReport",
    "HttpClient",
    "HttpClientOptions",
    "IdempotencyStore",
    "InMemoryBlobStore",
    "InMemoryIdempotencyStore",
    "InMemoryRepository",
    "InternalError",
    "NotFoundError",
    "Ok",
    "PresignOptions",
    "ProblemDetails",
    "PutOptions",
    "RateLimitedError",
    "Repository",
    "Result",
    "RetryOptions",
    "ServiceUnavailableError",
    "StoredResponse",
    "UnauthorizedError",
    "ValidationError",
    "check_health",
    "configure_logging",
    "err",
    "from_awaitable",
    "from_callable",
    "get_logger",
    "is_err",
    "is_ok",
    "load_config",
    "map_ok",
    "ok",
    "to_app_error",
    "unwrap",
    "unwrap_or",
    "with_idempotency",
    "with_request_id",
]
