# Backstage Software Catalog descriptor (Spotify).
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: marketplace-mobile
  annotations:
    getexp.dev/golden-path: mobile
spec:
  type: mobile-app
  lifecycle: experimental
  owner: unknown
